name: Render Deploy

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Docker
        run: |
          docker build -t my-app .

      - name: Deploy no Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/v1/services/srv-ct941456l47c73amjg5g/deploy \
            -H "Authorization: Bearer $RENDER_API_KEY"
